services:
  common:
    env_file:
      - .env
    container_name: census_backend
    restart: always
    build: .
    ports:
      - '$PORT:$PORT'
    links:
      - postgres
  postgres:
    image: postgres
    container_name: census_postgres
    restart: always
    environment:
      DB_DATABASE: '${DB_DATABASE}'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: census@123
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - '5433:5432'
    expose:
      - '5433'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: census_pgadmin
    image: dpage/pgadmin4
    ports:
      - '8081:80'
    volumes:
      - ~/census-pgadmin-data:/root/.pgadmin
    env_file:
      - .env
    links:
      - postgres

  redis-server:
    image: redis
    container_name: census_redis
    ports:
      - '6380:6379'
    volumes:
      - ~/census-redis-service/config/redis.conf:/redis.conf
    command: ['redis-server', '/redis.conf']

volumes:
  postgres_data:
    driver: local
