networks:
  attendance_network:
    driver: bridge

services:
  app:
    container_name: attendance_backend
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - '${PORT:-3001}:${PORT:-3001}'
    depends_on:
      redis:
        condition: service_started
    networks:
      - attendance_network

  # Uncomment below if using local PostgreSQL instead of Neon DB
  # postgres:
  #   image: postgres:15
  #   container_name: attendance_postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: '${DB_DATABASE}'
  #     POSTGRES_USER: '${DB_USERNAME:-postgres}'
  #     POSTGRES_PASSWORD: '${DB_PASSWORD:-attendance@123}'
  #     TZ: 'GMT'
  #     PGTZ: 'GMT'
  #   ports:
  #     - '5434:5432'
  #   env_file:
  #     - .env
  #   volumes:
  #     - attendance_postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME:-postgres}']
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - attendance_network

  # pgadmin:
  #   container_name: attendance_pgadmin
  #   image: dpage/pgadmin4
  #   restart: always
  #   ports:
  #     - '8082:80'
  #   volumes:
  #     - ~/attendance_pgadmin_data:/var/lib/pgadmin
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #   networks:
  #     - attendance_network

  redis:
    image: redis:alpine
    container_name: attendance_redis
    restart: always
    ports:
      - '6381:6379'
    volumes:
      - attendance_redis_data:/data
    command: ['redis-server', '--appendonly', 'yes']
    networks:
      - attendance_network

volumes:
  # attendance_postgres_data:
  #   driver: local
  # attendance_pgadmin_data:
  #   driver: local
  attendance_redis_data:
    driver: local
